# all configuration options with their defaults shown below:

# $configDir == <home directory>/.datascrapers

# API Key used to connect to EIA.gov
EIA_APIKey: #set to Thomas' key

# print the EIA output to screen
printData: false

# save Pandas DataFrame to a CSV file
saveCSVFile: true
# where that CSV file is located
CSVFilePath: #$configDir/EnergyData.csv

# save JSON converted DataFrame to a JSON file
saveJSONFile: true
# where that JSON file is located
JSONFilePath: #$configDir/EnergyData.json

# save Pandas DataFrame to Google Firestore database 
saveToDatabase: true
# where the Google Firestore credentials file is located
firestoreKeyPath: #$configDir/firestoreCreds.json

# how many days of forecasting data to keep in the database, in days
# NOTE: default of 0 means to keep one script execution's worth of days (which starts at yesterday's date)
rotateDatabase: 0
